"""Compatibility imports for geometry moved to the shared domain layer."""

from pedal_drill.geometry import (
    CalibrationLine,
    CalibrationOrientation,
    Capsule,
    CapsulePath,
    CircularArc,
    EnclosureOverview,
    FaceTransform,
    OverviewFace,
    PREFERRED_CALIBRATION_LENGTHS_MM,
    Rectangle,
    calibration_lines,
    capsule_bounds,
    capsule_for_slot,
    capsule_path,
    circle_bounds,
    enclosure_overview_geometry,
    face_bounds,
    face_corner_radius,
    face_outline,
    face_point,
    line_bounds,
    select_calibration_length,
    transform_overview_capsule,
)

__all__ = [
    "Capsule",
    "CapsulePath",
    "CircularArc",
    "CalibrationLine",
    "CalibrationOrientation",
    "EnclosureOverview",
    "FaceTransform",
    "OverviewFace",
    "PREFERRED_CALIBRATION_LENGTHS_MM",
    "Rectangle",
    "calibration_lines",
    "capsule_bounds",
    "capsule_for_slot",
    "capsule_path",
    "circle_bounds",
    "face_bounds",
    "face_corner_radius",
    "face_outline",
    "face_point",
    "enclosure_overview_geometry",
    "line_bounds",
    "select_calibration_length",
    "transform_overview_capsule",
]
